In [378]:
from pathlib import Path

pr_folder = Path("data/PR")

pr_files = sorted(pr_folder.rglob("*.csv"))

print(len(pr_files))

print(pr_files[:])

197
[PosixPath('data/PR/2019-07/2019-07-01.csv'), PosixPath('data/PR/2019-07/2019-07-06.csv'), PosixPath('data/PR/2019-07/2019-07-11.csv'), PosixPath('data/PR/2019-07/2019-07-16.csv'), PosixPath('data/PR/2019-07/2019-07-21.csv'), PosixPath('data/PR/2019-07/2019-07-26.csv'), PosixPath('data/PR/2019-07/2019-07-31.csv'), PosixPath('data/PR/2019-08/2019-08-05.csv'), PosixPath('data/PR/2019-08/2019-08-10.csv'), PosixPath('data/PR/2019-08/2019-08-15.csv'), PosixPath('data/PR/2019-08/2019-08-20.csv'), PosixPath('data/PR/2019-08/2019-08-25.csv'), PosixPath('data/PR/2019-08/2019-08-30.csv'), PosixPath('data/PR/2019-09/2019-09-04.csv'), PosixPath('data/PR/2019-09/2019-09-09.csv'), PosixPath('data/PR/2019-09/2019-09-14.csv'), PosixPath('data/PR/2019-09/2019-09-19.csv'), PosixPath('data/PR/2019-09/2019-09-24.csv'), PosixPath('data/PR/2019-09/2019-09-29.csv'), PosixPath('data/PR/2019-10/2019-10-04.csv'), PosixPath('data/PR/2019-10/2019-10-09.csv'), PosixPath('data/PR/2019-10/2019-10-14.csv'), PosixPath('data/PR/2019-10/2019-10-19.csv'), PosixPath('data/PR/2019-10/2019-10-24.csv'), PosixPath('data/PR/2019-10/2019-10-29.csv'), PosixPath('data/PR/2019-11/2019-11-03.csv'), PosixPath('data/PR/2019-11/2019-11-08.csv'), PosixPath('data/PR/2019-11/2019-11-13.csv'), PosixPath('data/PR/2019-11/2019-11-18.csv'), PosixPath('data/PR/2019-11/2019-11-23.csv'), PosixPath('data/PR/2019-11/2019-11-28.csv'), PosixPath('data/PR/2019-12/2019-12-03.csv'), PosixPath('data/PR/2019-12/2019-12-08.csv'), PosixPath('data/PR/2019-12/2019-12-13.csv'), PosixPath('data/PR/2019-12/2019-12-18.csv'), PosixPath('data/PR/2019-12/2019-12-23.csv'), PosixPath('data/PR/2019-12/2019-12-28.csv'), PosixPath('data/PR/2020-01/2020-01-02.csv'), PosixPath('data/PR/2020-01/2020-01-07.csv'), PosixPath('data/PR/2020-01/2020-01-12.csv'), PosixPath('data/PR/2020-01/2020-01-17.csv'), PosixPath('data/PR/2020-01/2020-01-22.csv'), PosixPath('data/PR/2020-01/2020-01-27.csv'), PosixPath('data/PR/2020-02/2020-02-01.csv'), PosixPath('data/PR/2020-02/2020-02-06.csv'), PosixPath('data/PR/2020-02/2020-02-11.csv'), PosixPath('data/PR/2020-02/2020-02-16.csv'), PosixPath('data/PR/2020-02/2020-02-21.csv'), PosixPath('data/PR/2020-02/2020-02-26.csv'), PosixPath('data/PR/2020-03/2020-03-02.csv'), PosixPath('data/PR/2020-03/2020-03-07.csv'), PosixPath('data/PR/2020-03/2020-03-12.csv'), PosixPath('data/PR/2020-03/2020-03-17.csv'), PosixPath('data/PR/2020-03/2020-03-22.csv'), PosixPath('data/PR/2020-03/2020-03-27.csv'), PosixPath('data/PR/2020-04/2020-04-01.csv'), PosixPath('data/PR/2020-04/2020-04-06.csv'), PosixPath('data/PR/2020-04/2020-04-11.csv'), PosixPath('data/PR/2020-04/2020-04-16.csv'), PosixPath('data/PR/2020-04/2020-04-21.csv'), PosixPath('data/PR/2020-04/2020-04-26.csv'), PosixPath('data/PR/2020-05/2020-05-01.csv'), PosixPath('data/PR/2020-05/2020-05-06.csv'), PosixPath('data/PR/2020-05/2020-05-11.csv'), PosixPath('data/PR/2020-05/2020-05-16.csv'), PosixPath('data/PR/2020-05/2020-05-21.csv'), PosixPath('data/PR/2020-05/2020-05-26.csv'), PosixPath('data/PR/2020-05/2020-05-31.csv'), PosixPath('data/PR/2020-06/2020-06-05.csv'), PosixPath('data/PR/2020-06/2020-06-10.csv'), PosixPath('data/PR/2020-06/2020-06-15.csv'), PosixPath('data/PR/2020-06/2020-06-20.csv'), PosixPath('data/PR/2020-06/2020-06-25.csv'), PosixPath('data/PR/2020-06/2020-06-30.csv'), PosixPath('data/PR/2020-07/2020-07-05.csv'), PosixPath('data/PR/2020-07/2020-07-10.csv'), PosixPath('data/PR/2020-07/2020-07-15.csv'), PosixPath('data/PR/2020-07/2020-07-20.csv'), PosixPath('data/PR/2020-07/2020-07-25.csv'), PosixPath('data/PR/2020-07/2020-07-30.csv'), PosixPath('data/PR/2020-08/2020-08-04.csv'), PosixPath('data/PR/2020-08/2020-08-09.csv'), PosixPath('data/PR/2020-08/2020-08-14.csv'), PosixPath('data/PR/2020-08/2020-08-19.csv'), PosixPath('data/PR/2020-08/2020-08-24.csv'), PosixPath('data/PR/2020-08/2020-08-29.csv'), PosixPath('data/PR/2020-09/2020-09-03.csv'), PosixPath('data/PR/2020-09/2020-09-08.csv'), PosixPath('data/PR/2020-09/2020-09-13.csv'), PosixPath('data/PR/2020-09/2020-09-18.csv'), PosixPath('data/PR/2020-09/2020-09-23.csv'), PosixPath('data/PR/2020-09/2020-09-28.csv'), PosixPath('data/PR/2020-10/2020-10-03.csv'), PosixPath('data/PR/2020-10/2020-10-08.csv'), PosixPath('data/PR/2020-10/2020-10-13.csv'), PosixPath('data/PR/2020-10/2020-10-18.csv'), PosixPath('data/PR/2020-10/2020-10-23.csv'), PosixPath('data/PR/2020-10/2020-10-28.csv'), PosixPath('data/PR/2020-11/2020-11-02.csv'), PosixPath('data/PR/2020-11/2020-11-07.csv'), PosixPath('data/PR/2020-11/2020-11-12.csv'), PosixPath('data/PR/2020-11/2020-11-17.csv'), PosixPath('data/PR/2020-11/2020-11-22.csv'), PosixPath('data/PR/2020-11/2020-11-27.csv'), PosixPath('data/PR/2020-12/2020-12-02.csv'), PosixPath('data/PR/2020-12/2020-12-07.csv'), PosixPath('data/PR/2020-12/2020-12-12.csv'), PosixPath('data/PR/2020-12/2020-12-17.csv'), PosixPath('data/PR/2020-12/2020-12-22.csv'), PosixPath('data/PR/2020-12/2020-12-27.csv'), PosixPath('data/PR/2021-01/2021-01-01.csv'), PosixPath('data/PR/2021-01/2021-01-06.csv'), PosixPath('data/PR/2021-01/2021-01-11.csv'), PosixPath('data/PR/2021-01/2021-01-16.csv'), PosixPath('data/PR/2021-01/2021-01-21.csv'), PosixPath('data/PR/2021-01/2021-01-26.csv'), PosixPath('data/PR/2021-01/2021-01-31.csv'), PosixPath('data/PR/2021-02/2021-02-05.csv'), PosixPath('data/PR/2021-02/2021-02-10.csv'), PosixPath('data/PR/2021-02/2021-02-15.csv'), PosixPath('data/PR/2021-02/2021-02-20.csv'), PosixPath('data/PR/2021-02/2021-02-25.csv'), PosixPath('data/PR/2021-03/2021-03-02.csv'), PosixPath('data/PR/2021-03/2021-03-07.csv'), PosixPath('data/PR/2021-03/2021-03-12.csv'), PosixPath('data/PR/2021-03/2021-03-17.csv'), PosixPath('data/PR/2021-03/2021-03-22.csv'), PosixPath('data/PR/2021-03/2021-03-27.csv'), PosixPath('data/PR/2021-04/2021-04-01.csv'), PosixPath('data/PR/2021-04/2021-04-20.csv'), PosixPath('data/PR/2021-04/2021-04-25.csv'), PosixPath('data/PR/2021-04/2021-04-30.csv'), PosixPath('data/PR/2021-05/2021-05-05.csv'), PosixPath('data/PR/2021-05/2021-05-10.csv'), PosixPath('data/PR/2021-05/2021-05-15.csv'), PosixPath('data/PR/2021-05/2021-05-20.csv'), PosixPath('data/PR/2021-05/2021-05-25.csv'), PosixPath('data/PR/2021-05/2021-05-30.csv'), PosixPath('data/PR/2021-06/2021-06-06.csv'), PosixPath('data/PR/2021-06/2021-06-11.csv'), PosixPath('data/PR/2021-06/2021-06-16.csv'), PosixPath('data/PR/2021-06/2021-06-21.csv'), PosixPath('data/PR/2021-06/2021-06-26.csv'), PosixPath('data/PR/2021-07/2021-07-01.csv'), PosixPath('data/PR/2021-07/2021-07-06.csv'), PosixPath('data/PR/2021-07/2021-07-11.csv'), PosixPath('data/PR/2021-07/2021-07-16.csv'), PosixPath('data/PR/2021-07/2021-07-21.csv'), PosixPath('data/PR/2021-07/2021-07-26.csv'), PosixPath('data/PR/2021-07/2021-07-31.csv'), PosixPath('data/PR/2021-08/2021-08-05.csv'), PosixPath('data/PR/2021-08/2021-08-10.csv'), PosixPath('data/PR/2021-08/2021-08-15.csv'), PosixPath('data/PR/2021-08/2021-08-20.csv'), PosixPath('data/PR/2021-08/2021-08-25.csv'), PosixPath('data/PR/2021-08/2021-08-30.csv'), PosixPath('data/PR/2021-09/2021-09-04.csv'), PosixPath('data/PR/2021-09/2021-09-09.csv'), PosixPath('data/PR/2021-09/2021-09-14.csv'), PosixPath('data/PR/2021-09/2021-09-19.csv'), PosixPath('data/PR/2021-09/2021-09-24.csv'), PosixPath('data/PR/2021-09/2021-09-29.csv'), PosixPath('data/PR/2021-10/2021-10-04.csv'), PosixPath('data/PR/2021-10/2021-10-09.csv'), PosixPath('data/PR/2021-10/2021-10-14.csv'), PosixPath('data/PR/2021-10/2021-10-19.csv'), PosixPath('data/PR/2021-10/2021-10-24.csv'), PosixPath('data/PR/2021-10/2021-10-29.csv'), PosixPath('data/PR/2021-11/2021-11-03.csv'), PosixPath('data/PR/2021-11/2021-11-08.csv'), PosixPath('data/PR/2021-11/2021-11-13.csv'), PosixPath('data/PR/2021-11/2021-11-18.csv'), PosixPath('data/PR/2021-11/2021-11-23.csv'), PosixPath('data/PR/2021-11/2021-11-28.csv'), PosixPath('data/PR/2021-12/2021-12-03.csv'), PosixPath('data/PR/2021-12/2021-12-08.csv'), PosixPath('data/PR/2021-12/2021-12-13.csv'), PosixPath('data/PR/2021-12/2021-12-18.csv'), PosixPath('data/PR/2021-12/2021-12-23.csv'), PosixPath('data/PR/2021-12/2021-12-28.csv'), PosixPath('data/PR/2022-01/2022-01-02.csv'), PosixPath('data/PR/2022-01/2022-01-07.csv'), PosixPath('data/PR/2022-01/2022-01-12.csv'), PosixPath('data/PR/2022-01/2022-01-17.csv'), PosixPath('data/PR/2022-01/2022-01-22.csv'), PosixPath('data/PR/2022-01/2022-01-27.csv'), PosixPath('data/PR/2022-02/2022-02-01.csv'), PosixPath('data/PR/2022-02/2022-02-06.csv'), PosixPath('data/PR/2022-02/2022-02-11.csv'), PosixPath('data/PR/2022-02/2022-02-16.csv'), PosixPath('data/PR/2022-02/2022-02-21.csv'), PosixPath('data/PR/2022-02/2022-02-26.csv'), PosixPath('data/PR/2022-03/2022-03-03.csv'), PosixPath('data/PR/2022-03/2022-03-08.csv'), PosixPath('data/PR/2022-03/2022-03-13.csv'), PosixPath('data/PR/2022-03/2022-03-18.csv'), PosixPath('data/PR/2022-03/2022-03-23.csv')]

In [379]:
import pandas as pd

sample_file = pr_files[0]

df = pd.read_csv(sample_file)

print(df)

         Date         PR
0  2019-07-01  69.575676
1  2019-07-02  79.314411
2  2019-07-03  61.020006
3  2019-07-04  83.262576
4  2019-07-05  82.124440

In [380]:
df.head()

         Date         PR
0  2019-07-01  69.575676
1  2019-07-02  79.314411
2  2019-07-03  61.020006
3  2019-07-04  83.262576
4  2019-07-05  82.124440

In [381]:
print(df.columns)

Index(['Date', 'PR'], dtype='object')

In [382]:
pr_data = []

for file in pr_files:
    df = pd.read_csv(file)

    pr_data.append(df)

    pr_df = pd.concat(
    pr_data,
    ignore_index=True
)

In [383]:
pr_df

           Date         PR
0    2019-07-01  69.575676
1    2019-07-02  79.314411
2    2019-07-03  61.020006
3    2019-07-04  83.262576
4    2019-07-05  82.124440
..          ...        ...
977  2022-03-20  81.632738
978  2022-03-21  71.057353
979  2022-03-22  81.631509
980  2022-03-23  71.906149
981  2022-03-24  79.911798

[982 rows x 2 columns]

In [384]:
pr_data

[         Date         PR
 0  2019-07-01  69.575676
 1  2019-07-02  79.314411
 2  2019-07-03  61.020006
 3  2019-07-04  83.262576
 4  2019-07-05  82.124440,
          Date         PR
 0  2019-07-06  82.764172
 1  2019-07-07  69.924507
 2  2019-07-08  84.789151
 3  2019-07-09  79.152393
 4  2019-07-10  69.085899,
          Date         PR
 0  2019-07-11  70.938886
 1  2019-07-12  72.456130
 2  2019-07-13  82.220913
 3  2019-07-14  71.861904
 4  2019-07-15  71.172819,
          Date         PR
 0  2019-07-16  74.833220
 1  2019-07-17  81.272453
 2  2019-07-18  62.768121
 3  2019-07-19  60.526905
 4  2019-07-20  76.949100,
          Date         PR
 0  2019-07-21  65.365044
 1  2019-07-22  60.242572
 2  2019-07-23  79.321120
 3  2019-07-24  75.446106
 4  2019-07-25  76.364219,
          Date         PR
 0  2019-07-26  70.662366
 1  2019-07-27  61.164194
 2  2019-07-28  68.921739
 3  2019-07-29  76.294480
 4  2019-07-30  78.962515,
          Date         PR
 0  2019-07-31  83.300605
 1  2019-08-01  63.135077
 2  2019-08-02  79.000137
 3  2019-08-03  67.116386
 4  2019-08-04  78.095733,
          Date         PR
 0  2019-08-05  82.721693
 1  2019-08-06  81.315773
 2  2019-08-07  77.852967
 3  2019-08-08  72.929129
 4  2019-08-09  76.339966,
          Date         PR
 0  2019-08-10  76.529665
 1  2019-08-11  74.379887
 2  2019-08-12  60.662169
 3  2019-08-13  81.588679
 4  2019-08-14  65.426746,
          Date         PR
 0  2019-08-15  67.919247
 1  2019-08-16  65.222719
 2  2019-08-17  81.270256
 3  2019-08-18  62.120264
 4  2019-08-19  73.389620,
          Date         PR
 0  2019-08-20  79.895162
 1  2019-08-21  79.637401
 2  2019-08-22  63.410052
 3  2019-08-23  61.572632
 4  2019-08-24  67.219303,
          Date         PR
 0  2019-08-25  63.195901
 1  2019-08-26  66.308965
 2  2019-08-27  60.722096
 3  2019-08-28  63.080593
 4  2019-08-29  71.601602,
          Date         PR
 0  2019-08-30  63.564458
 1  2019-08-31  77.711231
 2  2019-09-01  62.141447
 3  2019-09-02  68.216782
 4  2019-09-03  66.449787,
          Date         PR
 0  2019-09-04  73.522797
 1  2019-09-05  65.591991
 2  2019-09-06  66.407012
 3  2019-09-07  71.924367
 4  2019-09-08  84.643575,
          Date         PR
 0  2019-09-09  75.989085
 1  2019-09-10  72.423889
 2  2019-09-11  84.228596
 3  2019-09-12  81.547864
 4  2019-09-13  80.217865,
          Date         PR
 0  2019-09-14  63.961177
 1  2019-09-15  69.296125
 2  2019-09-16  63.651625
 3  2019-09-17  61.674365
 4  2019-09-18  71.475316,
          Date         PR
 0  2019-09-19  72.714704
 1  2019-09-20  76.017073
 2  2019-09-21  82.283554
 3  2019-09-22  72.490296
 4  2019-09-23  76.804684,
          Date         PR
 0  2019-09-24  65.943588
 1  2019-09-25  77.599669
 2  2019-09-26  78.683193
 3  2019-09-27  80.318289
 4  2019-09-28  82.979367,
          Date         PR
 0  2019-09-29  76.079073
 1  2019-09-30  84.597464
 2  2019-10-01  79.926904
 3  2019-10-02  79.626105
 4  2019-10-03  65.922352,
          Date         PR
 0  2019-10-04  66.654182
 1  2019-10-05  76.601606
 2  2019-10-06  76.558817
 3  2019-10-07  83.779569
 4  2019-10-08  83.614714,
          Date         PR
 0  2019-10-09  75.661404
 1  2019-10-10  80.048705
 2  2019-10-11  70.298084
 3  2019-10-12  81.902210
 4  2019-10-13  73.258209,
          Date         PR
 0  2019-10-14  66.728835
 1  2019-10-15  76.577874
 2  2019-10-16  77.065589
 3  2019-10-17  81.460227
 4  2019-10-18  73.770755,
          Date         PR
 0  2019-10-19  72.745357
 1  2019-10-20  66.347549
 2  2019-10-21  66.414909
 3  2019-10-22  63.296550
 4  2019-10-23  69.107989,
          Date         PR
 0  2019-10-24  61.902494
 1  2019-10-25  64.609799
 2  2019-10-26  63.869731
 3  2019-10-27  71.297374
 4  2019-10-28  67.229867,
          Date         PR
 0  2019-10-29  70.373432
 1  2019-10-30  68.121645
 2  2019-10-31  77.648309
 3  2019-11-01  77.834582
 4  2019-11-02  64.802906,
          Date         PR
 0  2019-11-03  74.453668
 1  2019-11-04  83.342010
 2  2019-11-05  75.873464
 3  2019-11-06  66.264122
 4  2019-11-07  71.068767,
          Date         PR
 0  2019-11-08  64.526562
 1  2019-11-09  70.124749
 2  2019-11-10  69.362953
 3  2019-11-11  64.810603
 4  2019-11-12  77.928440,
          Date         PR
 0  2019-11-13  69.522007
 1  2019-11-14  84.966158
 2  2019-11-15  79.548010
 3  2019-11-16  82.331744
 4  2019-11-17  84.411068,
          Date         PR
 0  2019-11-18  65.072272
 1  2019-11-19  62.043071
 2  2019-11-20  72.248618
 3  2019-11-21  76.424632
 4  2019-11-22  71.749049,
          Date         PR
 0  2019-11-23  74.736601
 1  2019-11-24  68.604814
 2  2019-11-25  73.438167
 3  2019-11-26  75.725247
 4  2019-11-27  81.487573,
          Date         PR
 0  2019-11-28  65.558489
 1  2019-11-29  78.723317
 2  2019-11-30  60.779787
 3  2019-12-01  61.252222
 4  2019-12-02  61.313096,
          Date         PR
 0  2019-12-03  60.400352
 1  2019-12-04  80.605645
 2  2019-12-05  73.778908
 3  2019-12-06  83.936236
 4  2019-12-07  80.916361,
          Date         PR
 0  2019-12-08  81.467904
 1  2019-12-09  61.307885
 2  2019-12-10  60.543772
 3  2019-12-11  68.950625
 4  2019-12-12  76.984294,
          Date         PR
 0  2019-12-13  75.902551
 1  2019-12-14  84.880598
 2  2019-12-15  76.072047
 3  2019-12-16  78.143476
 4  2019-12-17  77.943467,
          Date         PR
 0  2019-12-18  70.368229
 1  2019-12-19  78.067140
 2  2019-12-20  64.691625
 3  2019-12-21  82.216763
 4  2019-12-22  60.492248,
          Date         PR
 0  2019-12-23  80.257371
 1  2019-12-24  67.744302
 2  2019-12-25  67.636233
 3  2019-12-26  75.194958
 4  2019-12-27  75.954714,
          Date         PR
 0  2019-12-28  76.324906
 1  2019-12-29  73.803008
 2  2019-12-30  84.087499
 3  2019-12-31  80.965020
 4  2020-01-01  83.707309,
          Date         PR
 0  2020-01-02  68.113111
 1  2020-01-03  63.188956
 2  2020-01-04  60.442371
 3  2020-01-05  81.863592
 4  2020-01-06  70.890088,
          Date         PR
 0  2020-01-07  67.392852
 1  2020-01-08  64.297924
 2  2020-01-09  65.625129
 3  2020-01-10  72.346557
 4  2020-01-11  65.559016,
          Date         PR
 0  2020-01-12  65.929913
 1  2020-01-13  67.911748
 2  2020-01-14  74.227279
 3  2020-01-15  69.692505
 4  2020-01-16  72.977465,
          Date         PR
 0  2020-01-17  80.583118
 1  2020-01-18  77.462479
 2  2020-01-19  66.242893
 3  2020-01-20  72.962448
 4  2020-01-21  82.201322,
          Date         PR
 0  2020-01-22  79.487462
 1  2020-01-23  83.052661
 2  2020-01-24  68.409948
 3  2020-01-25  76.618271
 4  2020-01-26  61.444329,
          Date         PR
 0  2020-01-27  84.428573
 1  2020-01-28  79.516415
 2  2020-01-29  74.376717
 3  2020-01-30  72.748312
 4  2020-01-31  74.598280,
          Date         PR
 0  2020-02-01  71.539140
 1  2020-02-02  81.083056
 2  2020-02-03  76.692088
 3  2020-02-04  60.077481
 4  2020-02-05  79.767986,
          Date         PR
 0  2020-02-06  68.615601
 1  2020-02-07  68.221907
 2  2020-02-08  67.145744
 3  2020-02-09  76.959768
 4  2020-02-10  81.435254,
          Date         PR
 0  2020-02-11  69.426335
 1  2020-02-12  64.038149
 2  2020-02-13  70.126442
 3  2020-02-14  82.650529
 4  2020-02-15  72.650612,
          Date         PR
 0  2020-02-16  75.541188
 1  2020-02-17  81.384233
 2  2020-02-18  77.906231
 3  2020-02-19  76.790415
 4  2020-02-20  83.896126,
          Date         PR
 0  2020-02-21  83.532099
 1  2020-02-22  69.681136
 2  2020-02-23  60.065305
 3  2020-02-24  62.667387
 4  2020-02-25  78.007197,
          Date         PR
 0  2020-02-26  65.723268
 1  2020-02-27  65.549400
 2  2020-02-28  64.565958
 3  2020-02-29  82.304829
 4  2020-03-01  74.889237,
          Date         PR
 0  2020-03-02  63.664294
 1  2020-03-03  72.616146
 2  2020-03-04  70.462457
 3  2020-03-05  62.782283
 4  2020-03-06  83.107854,
          Date         PR
 0  2020-03-07  62.563845
 1  2020-03-08  78.412017
 2  2020-03-09  70.015541
 3  2020-03-10  79.593057
 4  2020-03-11  70.738581,
          Date         PR
 0  2020-03-12  61.868017
 1  2020-03-13  82.279152
 2  2020-03-14  75.004594
 3  2020-03-15  64.783372
 4  2020-03-16  81.326105,
          Date         PR
 0  2020-03-17  66.795938
 1  2020-03-18  74.956541
 2  2020-03-19  73.802553
 3  2020-03-20  70.694091
 4  2020-03-21  81.536837,
          Date         PR
 0  2020-03-22  72.198136
 1  2020-03-23  77.861827
 2  2020-03-24  77.598430
 3  2020-03-25  66.465840
 4  2020-03-26  65.642955,
          Date         PR
 0  2020-03-27  78.164737
 1  2020-03-28  73.167906
 2  2020-03-29  78.508088
 3  2020-03-30  75.836934
 4  2020-03-31  60.672264,
          Date         PR
 0  2020-04-01  82.114123
 1  2020-04-02  74.559280
 2  2020-04-03  66.575087
 3  2020-04-04  62.875709
 4  2020-04-05  75.322292,
          Date         PR
 0  2020-04-06  81.683138
 1  2020-04-07  61.784064
 2  2020-04-08  77.172344
 3  2020-04-09  60.879389
 4  2020-04-10  71.282577,
          Date         PR
 0  2020-04-11  82.414764
 1  2020-04-12  76.130166
 2  2020-04-13  75.913249
 3  2020-04-14  70.207916
 4  2020-04-15  66.796227,
          Date         PR
 0  2020-04-16  77.390326
 1  2020-04-17  84.389209
 2  2020-04-18  77.602844
 3  2020-04-19  80.898202
 4  2020-04-20  79.294846,
          Date         PR
 0  2020-04-21  76.039520
 1  2020-04-22  77.483346
 2  2020-04-23  62.827069
 3  2020-04-24  84.121803
 4  2020-04-25  65.110020,
          Date         PR
 0  2020-04-26  75.441461
 1  2020-04-27  81.053570
 2  2020-04-28  64.640805
 3  2020-04-29  74.858876
 4  2020-04-30  63.159587,
          Date         PR
 0  2020-05-01  66.452678
 1  2020-05-02  72.701994
 2  2020-05-03  61.520432
 3  2020-05-04  83.577012
 4  2020-05-05  72.700316,
          Date         PR
 0  2020-05-06  64.166162
 1  2020-05-07  73.664416
 2  2020-05-08  79.277412
 3  2020-05-09  75.533166
 4  2020-05-10  77.483599,
          Date         PR
 0  2020-05-11  62.990928
 1  2020-05-12  83.669465
 2  2020-05-13  61.290045
 3  2020-05-14  79.666221
 4  2020-05-15  73.668810,
          Date         PR
 0  2020-05-16  60.203111
 1  2020-05-17  70.906090
 2  2020-05-18  74.526854
 3  2020-05-19  67.261147
 4  2020-05-20  70.213612,
          Date         PR
 0  2020-05-21  82.327111
 1  2020-05-22  80.677901
 2  2020-05-23  62.749545
 3  2020-05-24  81.823154
 4  2020-05-25  75.916768,
          Date         PR
 0  2020-05-26  67.164327
 1  2020-05-27  75.598299
 2  2020-05-28  60.144446
 3  2020-05-29  78.118113
 4  2020-05-30  74.375395,
          Date         PR
 0  2020-05-31  79.160486
 1  2020-06-01  71.534460
 2  2020-06-02  64.086462
 3  2020-06-03  80.387180
 4  2020-06-04  60.822400,
          Date         PR
 0  2020-06-05  75.277568
 1  2020-06-06  80.050872
 2  2020-06-07  76.954854
 3  2020-06-08  77.230576
 4  2020-06-09  61.452267,
          Date         PR
 0  2020-06-10  80.561772
 1  2020-06-11  80.491673
 2  2020-06-12  76.099157
 3  2020-06-13  79.121390
 4  2020-06-14  69.289329,
          Date         PR
 0  2020-06-15  81.968499
 1  2020-06-16  77.384202
 2  2020-06-17  80.786333
 3  2020-06-18  70.696566
 4  2020-06-19  63.210016,
          Date         PR
 0  2020-06-20  65.501433
 1  2020-06-21  60.590291
 2  2020-06-22  71.524593
 3  2020-06-23  76.836229
 4  2020-06-24  65.047042,
          Date         PR
 0  2020-06-25  70.154573
 1  2020-06-26  74.315458
 2  2020-06-27  74.963568
 3  2020-06-28  77.374865
 4  2020-06-29  70.471282,
          Date         PR
 0  2020-06-30  65.038548
 1  2020-07-01  60.270227
 2  2020-07-02  72.572011
 3  2020-07-03  60.525034
 4  2020-07-04  69.596640,
          Date         PR
 0  2020-07-05  61.416844
 1  2020-07-06  60.636864
 2  2020-07-07  70.179503
 3  2020-07-08  70.984295
 4  2020-07-09  62.525898,
          Date         PR
 0  2020-07-10  79.042379
 1  2020-07-11  61.039876
 2  2020-07-12  83.209476
 3  2020-07-13  79.822617
 4  2020-07-14  83.212322,
          Date         PR
 0  2020-07-15  82.876033
 1  2020-07-16  84.723396
 2  2020-07-17  70.176377
 3  2020-07-18  63.416371
 4  2020-07-19  74.516635,
          Date         PR
 0  2020-07-20  61.606754
 1  2020-07-21  74.381640
 2  2020-07-22  68.789970
 3  2020-07-23  80.347686
 4  2020-07-24  83.213775,
          Date         PR
 0  2020-07-25  63.958634
 1  2020-07-26  74.817887
 2  2020-07-27  78.847696
 3  2020-07-28  73.539164
 4  2020-07-29  84.274999,
          Date         PR
 0  2020-07-30  76.336378
 1  2020-07-31  81.893874
 2  2020-08-01  60.483251
 3  2020-08-02  75.234996
 4  2020-08-03  68.368156,
          Date         PR
 0  2020-08-04  66.821870
 1  2020-08-05  78.122178
 2  2020-08-06  83.730387
 3  2020-08-07  83.804508
 4  2020-08-08  67.597836,
          Date         PR
 0  2020-08-09  66.909404
 1  2020-08-10  70.686437
 2  2020-08-11  80.916267
 3  2020-08-12  63.180271
 4  2020-08-13  70.542518,
          Date         PR
 0  2020-08-14  62.437403
 1  2020-08-15  68.059502
 2  2020-08-16  64.512316
 3  2020-08-17  83.381447
 4  2020-08-18  83.278859,
          Date         PR
 0  2020-08-19  70.803702
 1  2020-08-20  72.012070
 2  2020-08-21  60.023886
 3  2020-08-22  65.393522
 4  2020-08-23  81.247460,
          Date         PR
 0  2020-08-24  82.813101
 1  2020-08-25  67.769778
 2  2020-08-26  63.016064
 3  2020-08-27  73.650526
 4  2020-08-28  81.095435,
          Date         PR
 0  2020-08-29  64.682133
 1  2020-08-30  76.039435
 2  2020-08-31  82.642783
 3  2020-09-01  77.268870
 4  2020-09-02  80.255305,
          Date         PR
 0  2020-09-03  79.114948
 1  2020-09-04  64.278299
 2  2020-09-05  79.500332
 3  2020-09-06  75.984136
 4  2020-09-07  65.233467,
          Date         PR
 0  2020-09-08  83.000130
 1  2020-09-09  70.812947
 2  2020-09-10  65.333082
 3  2020-09-11  74.157844
 4  2020-09-12  63.677239,
          Date         PR
 0  2020-09-13  77.097469
 1  2020-09-14  66.507269
 2  2020-09-15  62.094066
 3  2020-09-16  66.693500
 4  2020-09-17  65.986261,
          Date         PR
 0  2020-09-18  65.814742
 1  2020-09-19  71.863348
 2  2020-09-20  76.092359
 3  2020-09-21  70.730959
 4  2020-09-22  72.615773,
          Date         PR
 0  2020-09-23  77.036138
 1  2020-09-24  80.768898
 2  2020-09-25  80.786410
 3  2020-09-26  71.775207
 4  2020-09-27  70.390301,
          Date         PR
 0  2020-09-28  60.587747
 1  2020-09-29  62.845062
 2  2020-09-30  83.188990
 3  2020-10-01  62.736747
 4  2020-10-02  73.718921,
          Date         PR
 0  2020-10-03  72.440140
 1  2020-10-04  76.938945
 2  2020-10-05  60.241675
 3  2020-10-06  80.874365
 4  2020-10-07  84.471002,
          Date         PR
 0  2020-10-08  84.980120
 1  2020-10-09  63.670234
 2  2020-10-10  80.630193
 3  2020-10-11  75.481203
 4  2020-10-12  74.213149,
          Date         PR
 0  2020-10-13  84.961800
 1  2020-10-14  67.800436
 2  2020-10-15  69.256229
 3  2020-10-16  70.503785
 4  2020-10-17  69.407747,
          Date         PR
 0  2020-10-18  74.012983
 1  2020-10-19  70.065268
 2  2020-10-20  63.291341
 3  2020-10-21  83.253067
 4  2020-10-22  82.907448,
          Date         PR
 0  2020-10-23  60.713079
 1  2020-10-24  62.309339
 2  2020-10-25  77.382916
 3  2020-10-26  78.274081
 4  2020-10-27  69.674187,
          Date         PR
 0  2020-10-28  80.494386
 1  2020-10-29  84.924373
 2  2020-10-30  81.171843
 3  2020-10-31  77.810532
 4  2020-11-01  66.216835,
          Date         PR
 0  2020-11-02  82.552766
 1  2020-11-03  84.689202
 2  2020-11-04  75.064316
 3  2020-11-05  74.904050
 4  2020-11-06  62.568874,
          Date         PR
 0  2020-11-07  70.666782
 1  2020-11-08  62.125522
 2  2020-11-09  75.877992
 3  2020-11-10  70.463390
 4  2020-11-11  81.403641,
          Date         PR
 0  2020-11-12  60.883555
 1  2020-11-13  69.399309
 2  2020-11-14  73.556793
 3  2020-11-15  84.106585
 4  2020-11-16  74.711883,
          Date         PR
 0  2020-11-17  64.972841
 1  2020-11-18  69.816647
 2  2020-11-19  62.280453
 3  2020-11-20  79.633751
 4  2020-11-21  64.552973,
          Date         PR
 0  2020-11-22  61.825164
 1  2020-11-23  62.580186
 2  2020-11-24  61.504981
 3  2020-11-25  80.423564
 4  2020-11-26  62.055393,
          Date         PR
 0  2020-11-27  80.884468
 1  2020-11-28  75.328614
 2  2020-11-29  63.040945
 3  2020-11-30  62.196277
 4  2020-12-01  68.556671,
          Date         PR
 0  2020-12-02  66.136570
 1  2020-12-03  76.051616
 2  2020-12-04  72.246977
 3  2020-12-05  77.035250
 4  2020-12-06  70.849672,
          Date         PR
 0  2020-12-07  82.584043
 1  2020-12-08  79.518185
 2  2020-12-09  74.403515
 3  2020-12-10  81.677462
 4  2020-12-11  75.571063,
          Date         PR
 0  2020-12-12  82.090095
 1  2020-12-13  75.256160
 2  2020-12-14  71.203182
 3  2020-12-15  67.292914
 4  2020-12-16  79.918001,
          Date         PR
 0  2020-12-17  80.040620
 1  2020-12-18  76.003280
 2  2020-12-19  78.985406
 3  2020-12-20  77.735731
 4  2020-12-21  72.063068,
          Date         PR
 0  2020-12-22  64.035724
 1  2020-12-23  82.280811
 2  2020-12-24  83.626825
 3  2020-12-25  62.184020
 4  2020-12-26  80.770430,
          Date         PR
 0  2020-12-27  66.817594
 1  2020-12-28  60.110233
 2  2020-12-29  64.948900
 3  2020-12-30  77.603579
 4  2020-12-31  63.369679,
          Date         PR
 0  2021-01-01  83.666417
 1  2021-01-02  61.515363
 2  2021-01-03  84.497785
 3  2021-01-04  78.414157
 4  2021-01-05  80.182364,
          Date         PR
 0  2021-01-06  84.907217
 1  2021-01-07  75.792121
 2  2021-01-08  64.430495
 3  2021-01-09  61.685521
 4  2021-01-10  64.243371,
          Date         PR
 0  2021-01-11  73.860843
 1  2021-01-12  60.146973
 2  2021-01-13  82.014818
 3  2021-01-14  82.797135
 4  2021-01-15  72.917561,
          Date         PR
 0  2021-01-16  69.193252
 1  2021-01-17  81.638697
 2  2021-01-18  65.784958
 3  2021-01-19  64.930657
 4  2021-01-20  61.893887,
          Date         PR
 0  2021-01-21  63.660002
 1  2021-01-22  60.287389
 2  2021-01-23  75.261889
 3  2021-01-24  66.906310
 4  2021-01-25  64.098119,
          Date         PR
 0  2021-01-26  66.819093
 1  2021-01-27  63.860667
 2  2021-01-28  69.444078
 3  2021-01-29  72.425138
 4  2021-01-30  75.613051,
          Date         PR
 0  2021-01-31  66.360061
 1  2021-02-01  66.924999
 2  2021-02-02  78.791422
 3  2021-02-03  72.967284
 4  2021-02-04  63.086908,
          Date         PR
 0  2021-02-05  80.020049
 1  2021-02-06  62.858215
 2  2021-02-07  77.562613
 3  2021-02-08  77.060228
 4  2021-02-09  68.223883,
          Date         PR
 0  2021-02-10  64.141479
 1  2021-02-11  63.868068
 2  2021-02-12  70.570746
 3  2021-02-13  78.762935
 4  2021-02-14  72.819632,
          Date         PR
 0  2021-02-15  61.697174
 1  2021-02-16  74.946311
 2  2021-02-17  75.831441
 3  2021-02-18  65.740103
 4  2021-02-19  84.334122,
          Date         PR
 0  2021-02-20  76.009959
 1  2021-02-21  77.801304
 2  2021-02-22  76.215681
 3  2021-02-23  81.554560
 4  2021-02-24  66.572062,
          Date         PR
 0  2021-02-25  79.130196
 1  2021-02-26  62.733199
 2  2021-02-27  71.441042
 3  2021-02-28  67.508661
 4  2021-03-01  61.559196,
          Date         PR
 0  2021-03-02  65.852898
 1  2021-03-03  82.273375
 2  2021-03-04  84.910113
 3  2021-03-05  64.107772
 4  2021-03-06  64.880611,
          Date         PR
 0  2021-03-07  75.199074
 1  2021-03-08  69.314582
 2  2021-03-09  72.339205
 3  2021-03-10  64.001591
 4  2021-03-11  76.618264,
          Date         PR
 0  2021-03-12  83.632224
 1  2021-03-13  80.617623
 2  2021-03-14  75.945276
 3  2021-03-15  76.221602
 4  2021-03-16  70.781686,
          Date         PR
 0  2021-03-17  75.736834
 1  2021-03-18  73.754551
 2  2021-03-19  73.133275
 3  2021-03-20  73.465853
 4  2021-03-21  61.185690,
          Date         PR
 0  2021-03-22  67.660427
 1  2021-03-23  80.582512
 2  2021-03-24  81.658935
 3  2021-03-25  77.533251
 4  2021-03-26  82.360268,
          Date         PR
 0  2021-03-27  69.515535

## GHI

In [385]:
from pathlib import Path

ghi_folder = Path("data/GHI")

ghi_files = sorted(ghi_folder.rglob("*.csv"))

print(len(ghi_files))

print(ghi_files[:])

197
[PosixPath('data/GHI/2019-07/2019-07-01.csv'), PosixPath('data/GHI/2019-07/2019-07-06.csv'), PosixPath('data/GHI/2019-07/2019-07-11.csv'), PosixPath('data/GHI/2019-07/2019-07-16.csv'), PosixPath('data/GHI/2019-07/2019-07-21.csv'), PosixPath('data/GHI/2019-07/2019-07-26.csv'), PosixPath('data/GHI/2019-07/2019-07-31.csv'), PosixPath('data/GHI/2019-08/2019-08-05.csv'), PosixPath('data/GHI/2019-08/2019-08-10.csv'), PosixPath('data/GHI/2019-08/2019-08-15.csv'), PosixPath('data/GHI/2019-08/2019-08-20.csv'), PosixPath('data/GHI/2019-08/2019-08-25.csv'), PosixPath('data/GHI/2019-08/2019-08-30.csv'), PosixPath('data/GHI/2019-09/2019-09-04.csv'), PosixPath('data/GHI/2019-09/2019-09-09.csv'), PosixPath('data/GHI/2019-09/2019-09-14.csv'), PosixPath('data/GHI/2019-09/2019-09-19.csv'), PosixPath('data/GHI/2019-09/2019-09-24.csv'), PosixPath('data/GHI/2019-09/2019-09-29.csv'), PosixPath('data/GHI/2019-10/2019-10-04.csv'), PosixPath('data/GHI/2019-10/2019-10-09.csv'), PosixPath('data/GHI/2019-10/2019-10-14.csv'), PosixPath('data/GHI/2019-10/2019-10-19.csv'), PosixPath('data/GHI/2019-10/2019-10-24.csv'), PosixPath('data/GHI/2019-10/2019-10-29.csv'), PosixPath('data/GHI/2019-11/2019-11-03.csv'), PosixPath('data/GHI/2019-11/2019-11-08.csv'), PosixPath('data/GHI/2019-11/2019-11-13.csv'), PosixPath('data/GHI/2019-11/2019-11-18.csv'), PosixPath('data/GHI/2019-11/2019-11-23.csv'), PosixPath('data/GHI/2019-11/2019-11-28.csv'), PosixPath('data/GHI/2019-12/2019-12-03.csv'), PosixPath('data/GHI/2019-12/2019-12-08.csv'), PosixPath('data/GHI/2019-12/2019-12-13.csv'), PosixPath('data/GHI/2019-12/2019-12-18.csv'), PosixPath('data/GHI/2019-12/2019-12-23.csv'), PosixPath('data/GHI/2019-12/2019-12-28.csv'), PosixPath('data/GHI/2020-01/2020-01-02.csv'), PosixPath('data/GHI/2020-01/2020-01-07.csv'), PosixPath('data/GHI/2020-01/2020-01-12.csv'), PosixPath('data/GHI/2020-01/2020-01-17.csv'), PosixPath('data/GHI/2020-01/2020-01-22.csv'), PosixPath('data/GHI/2020-01/2020-01-27.csv'), PosixPath('data/GHI/2020-02/2020-02-01.csv'), PosixPath('data/GHI/2020-02/2020-02-06.csv'), PosixPath('data/GHI/2020-02/2020-02-11.csv'), PosixPath('data/GHI/2020-02/2020-02-16.csv'), PosixPath('data/GHI/2020-02/2020-02-21.csv'), PosixPath('data/GHI/2020-02/2020-02-26.csv'), PosixPath('data/GHI/2020-03/2020-03-02.csv'), PosixPath('data/GHI/2020-03/2020-03-07.csv'), PosixPath('data/GHI/2020-03/2020-03-12.csv'), PosixPath('data/GHI/2020-03/2020-03-17.csv'), PosixPath('data/GHI/2020-03/2020-03-22.csv'), PosixPath('data/GHI/2020-03/2020-03-27.csv'), PosixPath('data/GHI/2020-04/2020-04-01.csv'), PosixPath('data/GHI/2020-04/2020-04-06.csv'), PosixPath('data/GHI/2020-04/2020-04-11.csv'), PosixPath('data/GHI/2020-04/2020-04-16.csv'), PosixPath('data/GHI/2020-04/2020-04-21.csv'), PosixPath('data/GHI/2020-04/2020-04-26.csv'), PosixPath('data/GHI/2020-05/2020-05-01.csv'), PosixPath('data/GHI/2020-05/2020-05-06.csv'), PosixPath('data/GHI/2020-05/2020-05-11.csv'), PosixPath('data/GHI/2020-05/2020-05-16.csv'), PosixPath('data/GHI/2020-05/2020-05-21.csv'), PosixPath('data/GHI/2020-05/2020-05-26.csv'), PosixPath('data/GHI/2020-05/2020-05-31.csv'), PosixPath('data/GHI/2020-06/2020-06-05.csv'), PosixPath('data/GHI/2020-06/2020-06-10.csv'), PosixPath('data/GHI/2020-06/2020-06-15.csv'), PosixPath('data/GHI/2020-06/2020-06-20.csv'), PosixPath('data/GHI/2020-06/2020-06-25.csv'), PosixPath('data/GHI/2020-06/2020-06-30.csv'), PosixPath('data/GHI/2020-07/2020-07-05.csv'), PosixPath('data/GHI/2020-07/2020-07-10.csv'), PosixPath('data/GHI/2020-07/2020-07-15.csv'), PosixPath('data/GHI/2020-07/2020-07-20.csv'), PosixPath('data/GHI/2020-07/2020-07-25.csv'), PosixPath('data/GHI/2020-07/2020-07-30.csv'), PosixPath('data/GHI/2020-08/2020-08-04.csv'), PosixPath('data/GHI/2020-08/2020-08-09.csv'), PosixPath('data/GHI/2020-08/2020-08-14.csv'), PosixPath('data/GHI/2020-08/2020-08-19.csv'), PosixPath('data/GHI/2020-08/2020-08-24.csv'), PosixPath('data/GHI/2020-08/2020-08-29.csv'), PosixPath('data/GHI/2020-09/2020-09-03.csv'), PosixPath('data/GHI/2020-09/2020-09-08.csv'), PosixPath('data/GHI/2020-09/2020-09-13.csv'), PosixPath('data/GHI/2020-09/2020-09-18.csv'), PosixPath('data/GHI/2020-09/2020-09-23.csv'), PosixPath('data/GHI/2020-09/2020-09-28.csv'), PosixPath('data/GHI/2020-10/2020-10-03.csv'), PosixPath('data/GHI/2020-10/2020-10-08.csv'), PosixPath('data/GHI/2020-10/2020-10-13.csv'), PosixPath('data/GHI/2020-10/2020-10-18.csv'), PosixPath('data/GHI/2020-10/2020-10-23.csv'), PosixPath('data/GHI/2020-10/2020-10-28.csv'), PosixPath('data/GHI/2020-11/2020-11-02.csv'), PosixPath('data/GHI/2020-11/2020-11-07.csv'), PosixPath('data/GHI/2020-11/2020-11-12.csv'), PosixPath('data/GHI/2020-11/2020-11-17.csv'), PosixPath('data/GHI/2020-11/2020-11-22.csv'), PosixPath('data/GHI/2020-11/2020-11-27.csv'), PosixPath('data/GHI/2020-12/2020-12-02.csv'), PosixPath('data/GHI/2020-12/2020-12-07.csv'), PosixPath('data/GHI/2020-12/2020-12-12.csv'), PosixPath('data/GHI/2020-12/2020-12-17.csv'), PosixPath('data/GHI/2020-12/2020-12-22.csv'), PosixPath('data/GHI/2020-12/2020-12-27.csv'), PosixPath('data/GHI/2021-01/2021-01-01.csv'), PosixPath('data/GHI/2021-01/2021-01-06.csv'), PosixPath('data/GHI/2021-01/2021-01-11.csv'), PosixPath('data/GHI/2021-01/2021-01-16.csv'), PosixPath('data/GHI/2021-01/2021-01-21.csv'), PosixPath('data/GHI/2021-01/2021-01-26.csv'), PosixPath('data/GHI/2021-01/2021-01-31.csv'), PosixPath('data/GHI/2021-02/2021-02-05.csv'), PosixPath('data/GHI/2021-02/2021-02-10.csv'), PosixPath('data/GHI/2021-02/2021-02-15.csv'), PosixPath('data/GHI/2021-02/2021-02-20.csv'), PosixPath('data/GHI/2021-02/2021-02-25.csv'), PosixPath('data/GHI/2021-03/2021-03-02.csv'), PosixPath('data/GHI/2021-03/2021-03-07.csv'), PosixPath('data/GHI/2021-03/2021-03-12.csv'), PosixPath('data/GHI/2021-03/2021-03-17.csv'), PosixPath('data/GHI/2021-03/2021-03-22.csv'), PosixPath('data/GHI/2021-03/2021-03-27.csv'), PosixPath('data/GHI/2021-04/2021-04-01.csv'), PosixPath('data/GHI/2021-04/2021-04-20.csv'), PosixPath('data/GHI/2021-04/2021-04-25.csv'), PosixPath('data/GHI/2021-04/2021-04-30.csv'), PosixPath('data/GHI/2021-05/2021-05-05.csv'), PosixPath('data/GHI/2021-05/2021-05-10.csv'), PosixPath('data/GHI/2021-05/2021-05-15.csv'), PosixPath('data/GHI/2021-05/2021-05-20.csv'), PosixPath('data/GHI/2021-05/2021-05-25.csv'), PosixPath('data/GHI/2021-05/2021-05-30.csv'), PosixPath('data/GHI/2021-06/2021-06-06.csv'), PosixPath('data/GHI/2021-06/2021-06-11.csv'), PosixPath('data/GHI/2021-06/2021-06-16.csv'), PosixPath('data/GHI/2021-06/2021-06-21.csv'), PosixPath('data/GHI/2021-06/2021-06-26.csv'), PosixPath('data/GHI/2021-07/2021-07-01.csv'), PosixPath('data/GHI/2021-07/2021-07-06.csv'), PosixPath('data/GHI/2021-07/2021-07-11.csv'), PosixPath('data/GHI/2021-07/2021-07-16.csv'), PosixPath('data/GHI/2021-07/2021-07-21.csv'), PosixPath('data/GHI/2021-07/2021-07-26.csv'), PosixPath('data/GHI/2021-07/2021-07-31.csv'), PosixPath('data/GHI/2021-08/2021-08-05.csv'), PosixPath('data/GHI/2021-08/2021-08-10.csv'), PosixPath('data/GHI/2021-08/2021-08-15.csv'), PosixPath('data/GHI/2021-08/2021-08-20.csv'), PosixPath('data/GHI/2021-08/2021-08-25.csv'), PosixPath('data/GHI/2021-08/2021-08-30.csv'), PosixPath('data/GHI/2021-09/2021-09-04.csv'), PosixPath('data/GHI/2021-09/2021-09-09.csv'), PosixPath('data/GHI/2021-09/2021-09-14.csv'), PosixPath('data/GHI/2021-09/2021-09-19.csv'), PosixPath('data/GHI/2021-09/2021-09-24.csv'), PosixPath('data/GHI/2021-09/2021-09-29.csv'), PosixPath('data/GHI/2021-10/2021-10-04.csv'), PosixPath('data/GHI/2021-10/2021-10-09.csv'), PosixPath('data/GHI/2021-10/2021-10-14.csv'), PosixPath('data/GHI/2021-10/2021-10-19.csv'), PosixPath('data/GHI/2021-10/2021-10-24.csv'), PosixPath('data/GHI/2021-10/2021-10-29.csv'), PosixPath('data/GHI/2021-11/2021-11-03.csv'), PosixPath('data/GHI/2021-11/2021-11-08.csv'), PosixPath('data/GHI/2021-11/2021-11-13.csv'), PosixPath('data/GHI/2021-11/2021-11-18.csv'), PosixPath('data/GHI/2021-11/2021-11-23.csv'), PosixPath('data/GHI/2021-11/2021-11-28.csv'), PosixPath('data/GHI/2021-12/2021-12-03.csv'), PosixPath('data/GHI/2021-12/2021-12-08.csv'), PosixPath('data/GHI/2021-12/2021-12-13.csv'), PosixPath('data/GHI/2021-12/2021-12-18.csv'), PosixPath('data/GHI/2021-12/2021-12-23.csv'), PosixPath('data/GHI/2021-12/2021-12-28.csv'), PosixPath('data/GHI/2022-01/2022-01-02.csv'), PosixPath('data/GHI/2022-01/2022-01-07.csv'), PosixPath('data/GHI/2022-01/2022-01-12.csv'), PosixPath('data/GHI/2022-01/2022-01-17.csv'), PosixPath('data/GHI/2022-01/2022-01-22.csv'), PosixPath('data/GHI/2022-01/2022-01-27.csv'), PosixPath('data/GHI/2022-02/2022-02-01.csv'), PosixPath('data/GHI/2022-02/2022-02-06.csv'), PosixPath('data/GHI/2022-02/2022-02-11.csv'), PosixPath('data/GHI/2022-02/2022-02-16.csv'), PosixPath('data/GHI/2022-02/2022-02-21.csv'), PosixPath('data/GHI/2022-02/2022-02-26.csv'), PosixPath('data/GHI/2022-03/2022-03-03.csv'), PosixPath('data/GHI/2022-03/2022-03-08.csv'), PosixPath('data/GHI/2022-03/2022-03-13.csv'), PosixPath('data/GHI/2022-03/2022-03-18.csv'), PosixPath('data/GHI/2022-03/2022-03-23.csv')]

In [386]:
ghi_data = []

for file in ghi_files:
    df = pd.read_csv(file)
    ghi_data.append(df)

ghi_df = pd.concat(
    ghi_data,
    ignore_index=True
)

In [387]:
ghi_df

           Date       GHI
0    2019-07-01  3.256608
1    2019-07-02  3.976767
2    2019-07-03  2.811867
3    2019-07-04  3.658408
4    2019-07-05  5.590683
..          ...       ...
977  2022-03-20  4.226183
978  2022-03-21  3.431675
979  2022-03-22  3.580492
980  2022-03-23  4.997617
981  2022-03-24  5.125050

[982 rows x 2 columns]

In [388]:
merged_df = pd.merge(
    pr_df,
    ghi_df,
    on="Date",
    how="inner"
)

In [389]:
print(type(merged_df))
print(merged_df)

<class 'pandas.core.frame.DataFrame'>
           Date         PR       GHI
0    2019-07-01  69.575676  3.256608
1    2019-07-02  79.314411  3.976767
2    2019-07-03  61.020006  2.811867
3    2019-07-04  83.262576  3.658408
4    2019-07-05  82.124440  5.590683
..          ...        ...       ...
977  2022-03-20  81.632738  4.226183
978  2022-03-21  71.057353  3.431675
979  2022-03-22  81.631509  3.580492
980  2022-03-23  71.906149  4.997617
981  2022-03-24  79.911798  5.125050

[982 rows x 3 columns]

In [390]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 982 entries, 0 to 981
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    982 non-null    object
 1   PR      982 non-null    float64
 2   GHI     982 non-null    float64
dtypes: float64(2), object(1)
memory usage: 23.1+ KB

In [391]:
merged_df.shape

(982, 3)

In [392]:
merged_df["Date"] = pd.to_datetime(merged_df["Date"])

In [393]:
merged_df.shape

(982, 3)

In [394]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 982 entries, 0 to 981
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    982 non-null    datetime64[ns]
 1   PR      982 non-null    float64
 2   GHI     982 non-null    float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 23.1 KB

In [395]:
merged_df = merged_df.sort_values("Date")
merged_df = merged_df.reset_index(drop=True)

In [396]:
merged_df

          Date         PR       GHI
0   2019-07-01  69.575676  3.256608
1   2019-07-02  79.314411  3.976767
2   2019-07-03  61.020006  2.811867
3   2019-07-04  83.262576  3.658408
4   2019-07-05  82.124440  5.590683
..         ...        ...       ...
977 2022-03-20  81.632738  4.226183
978 2022-03-21  71.057353  3.431675
979 2022-03-22  81.631509  3.580492
980 2022-03-23  71.906149  4.997617
981 2022-03-24  79.911798  5.125050

[982 rows x 3 columns]

In [397]:
merged_df.to_csv("data/preprocessed_data.csv", index=False)

In [398]:
pr_df.shape

(982, 2)

In [399]:
pr_df.columns

Index(['Date', 'PR'], dtype='object')

In [400]:
ghi_df.shape

(982, 2)

In [401]:
ghi_df.columns

Index(['Date', 'GHI'], dtype='object')

In [402]:
pr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 982 entries, 0 to 981
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    982 non-null    object
 1   PR      982 non-null    float64
dtypes: float64(1), object(1)
memory usage: 15.5+ KB

In [403]:
ghi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 982 entries, 0 to 981
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    982 non-null    object
 1   GHI     982 non-null    float64
dtypes: float64(1), object(1)
memory usage: 15.5+ KB

In [404]:
print(pr_df.duplicated().sum())
print(ghi_df.duplicated().sum())

0
0

In [405]:
print(pr_df["Date"].duplicated().sum())
print(ghi_df["Date"].duplicated().sum())

0
0

In [406]:
print(merged_df.shape)
print(merged_df.head())
print(merged_df.tail())

(982, 3)
        Date         PR       GHI
0 2019-07-01  69.575676  3.256608
1 2019-07-02  79.314411  3.976767
2 2019-07-03  61.020006  2.811867
3 2019-07-04  83.262576  3.658408
4 2019-07-05  82.124440  5.590683
          Date         PR       GHI
977 2022-03-20  81.632738  4.226183
978 2022-03-21  71.057353  3.431675
979 2022-03-22  81.631509  3.580492
980 2022-03-23  71.906149  4.997617
981 2022-03-24  79.911798  5.125050

In [410]:
check = pd.read_csv("data/preprocessed_data.csv")
check.head()

         Date         PR       GHI
0  2019-07-01  69.575676  3.256608
1  2019-07-02  79.314411  3.976767
2  2019-07-03  61.020006  2.811867
3  2019-07-04  83.262576  3.658408
4  2019-07-05  82.124440  5.590683

In [408]:
check.shape

(982, 3)